
/*
 * Dylan Moore  
 * Oct 28 2019  
 * simple program utilising math methods
 */
/**
 *
 * @author dymoo6791
 */
public class StringFrame extends javax.swing.JFrame {

    /**
     * Creates new form mathFrame
     */
    public StringFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lengthBtn = new javax.swing.JButton();
        lengthTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lengthLbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        capsTF = new javax.swing.JTextField();
        capsBtn = new javax.swing.JButton();
        capsLbl = new javax.swing.JLabel();
        fourthCharTF = new javax.swing.JTextField();
        identicalBtn = new javax.swing.JButton();
        identicalLbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        identicalTF2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fourthCharBtn = new javax.swing.JButton();
        fourthCharLbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        identicalTF1 = new javax.swing.JTextField();
        locateTF2 = new javax.swing.JTextField();
        locateBtn = new javax.swing.JButton();
        locateLbl = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        displayLocationTF = new javax.swing.JTextField();
        displayLocationBtn = new javax.swing.JButton();
        displayLocationLbl = new javax.swing.JLabel();
        replaceTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        replaceBtn = new javax.swing.JButton();
        replaceLbl = new javax.swing.JLabel();
        locateTF1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lengthBtn.setText("Length");
        lengthBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lengthBtnActionPerformed(evt);
            }
        });
        jPanel1.add(lengthBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        lengthTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lengthTFActionPerformed(evt);
            }
        });
        jPanel1.add(lengthTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 150, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("String Methods");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 230, -1));

        jLabel2.setText("Enter a string. The program will change all characters to uppercase");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        lengthLbl.setText("------------------");
        jPanel1.add(lengthLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 190, 20));

        jLabel3.setText("Enter two numbers and click the button. The program will display the largest number");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        capsTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capsTFActionPerformed(evt);
            }
        });
        jPanel1.add(capsTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 150, -1));

        capsBtn.setText("To Uppercase");
        capsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capsBtnActionPerformed(evt);
            }
        });
        jPanel1.add(capsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        capsLbl.setText("------------------");
        jPanel1.add(capsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 190, 20));

        fourthCharTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourthCharTFActionPerformed(evt);
            }
        });
        jPanel1.add(fourthCharTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 150, -1));

        identicalBtn.setText("Identical?");
        identicalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identicalBtnActionPerformed(evt);
            }
        });
        jPanel1.add(identicalBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));

        identicalLbl.setText("------------------");
        jPanel1.add(identicalLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 190, 20));

        jLabel4.setText("Enter a string and a letter. The program will output wether or not the letter is in the string");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        identicalTF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identicalTF2ActionPerformed(evt);
            }
        });
        jPanel1.add(identicalTF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 80, -1));

        jLabel5.setText("Enter a string. The program will identify the 4th character");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        fourthCharBtn.setText("4th char");
        fourthCharBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourthCharBtnActionPerformed(evt);
            }
        });
        jPanel1.add(fourthCharBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        fourthCharLbl.setText("------------------");
        jPanel1.add(fourthCharLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 190, 20));

        jLabel6.setText("Enter to Strings. The program will output wether they are identical or not");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        identicalTF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identicalTF1ActionPerformed(evt);
            }
        });
        jPanel1.add(identicalTF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 90, -1));

        locateTF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locateTF2ActionPerformed(evt);
            }
        });
        jPanel1.add(locateTF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 40, -1));

        locateBtn.setText("Letter found?");
        locateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locateBtnActionPerformed(evt);
            }
        });
        jPanel1.add(locateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, -1, -1));

        locateLbl.setText("------------------");
        jPanel1.add(locateLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 190, 20));

        jLabel7.setText("Enter a String that is atleast 8 characters long. The program will display 4 to 6 characters");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        displayLocationTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayLocationTFActionPerformed(evt);
            }
        });
        jPanel1.add(displayLocationTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 180, -1));

        displayLocationBtn.setText("Characters 4 to 6");
        displayLocationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayLocationBtnActionPerformed(evt);
            }
        });
        jPanel1.add(displayLocationBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, -1, -1));

        displayLocationLbl.setText("------------------");
        jPanel1.add(displayLocationLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, 190, 20));

        replaceTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaceTFActionPerformed(evt);
            }
        });
        jPanel1.add(replaceTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 180, -1));

        jLabel8.setText("Enter a string with atleast one \"a\". The program will replace the \"a\" with an \"x\"");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        replaceBtn.setText("Replace \"a\"");
        replaceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaceBtnActionPerformed(evt);
            }
        });
        jPanel1.add(replaceBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, -1, -1));

        replaceLbl.setText("------------------");
        jPanel1.add(replaceLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 510, 190, 20));

        locateTF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locateTF1ActionPerformed(evt);
            }
        });
        jPanel1.add(locateTF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 120, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lengthTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lengthTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lengthTFActionPerformed

    private void lengthBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lengthBtnActionPerformed
        String input = (lengthTF.getText());
        int amount = input.length();
        String length = String.valueOf(amount);
        lengthLbl.setText(length);
    }//GEN-LAST:event_lengthBtnActionPerformed

    private void capsTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capsTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_capsTFActionPerformed

    private void capsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capsBtnActionPerformed
        String input = (capsTF.getText());
        String upper = input.toUpperCase();
        capsLbl.setText(upper);
    }//GEN-LAST:event_capsBtnActionPerformed

    private void fourthCharTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourthCharTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fourthCharTFActionPerformed

    private void identicalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identicalBtnActionPerformed
        String input1 = (identicalTF1.getText());
        String input2 = (identicalTF2.getText());
        boolean output = input1.equals(input2);
        if (output == true) {
            String yes = "Yes";
            identicalLbl.setText(yes);
        } else {
            identicalLbl.setText("No");
        }

    }//GEN-LAST:event_identicalBtnActionPerformed

    private void identicalTF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identicalTF2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_identicalTF2ActionPerformed

    private void identicalTF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identicalTF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_identicalTF1ActionPerformed

    private void fourthCharBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourthCharBtnActionPerformed
        String input = (fourthCharTF.getText());
        char fourth = (input.charAt(3));
        String change = Character.toString(fourth);
        fourthCharLbl.setText(change);
    }//GEN-LAST:event_fourthCharBtnActionPerformed

    private void locateTF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locateTF2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locateTF2ActionPerformed

    private void locateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locateBtnActionPerformed
        String input = locateTF1.getText();
        String locate = locateTF2.getText();
        int output = input.indexOf(locate);
        String location = String.valueOf(output);
        locateLbl.setText("The first " + locate + " is at position " + location);
    }//GEN-LAST:event_locateBtnActionPerformed

    private void displayLocationTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayLocationTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayLocationTFActionPerformed

    private void displayLocationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayLocationBtnActionPerformed
        String locate = displayLocationTF.getText();
        char location4 = locate.charAt(4);
        char location5 = locate.charAt(5);
        char location6 = locate.charAt(6);
        String output=String.valueOf(location4);
        String output1=String.valueOf(location5);
        String output2=String.valueOf(location6);
        displayLocationLbl.setText(output +","+ output1 +","+ output2);
    }//GEN-LAST:event_displayLocationBtnActionPerformed

    private void replaceTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_replaceTFActionPerformed

    private void replaceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceBtnActionPerformed
        String input = (replaceTF.getText());
        String replace = input.replace("a","x");
        replaceLbl.setText(replace);
    }//GEN-LAST:event_replaceBtnActionPerformed

    private void locateTF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locateTF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locateTF1ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StringFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StringFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StringFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StringFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StringFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton capsBtn;
    private javax.swing.JLabel capsLbl;
    private javax.swing.JTextField capsTF;
    private javax.swing.JButton displayLocationBtn;
    private javax.swing.JLabel displayLocationLbl;
    private javax.swing.JTextField displayLocationTF;
    private javax.swing.JButton fourthCharBtn;
    private javax.swing.JLabel fourthCharLbl;
    private javax.swing.JTextField fourthCharTF;
    private javax.swing.JButton identicalBtn;
    private javax.swing.JLabel identicalLbl;
    private javax.swing.JTextField identicalTF1;
    private javax.swing.JTextField identicalTF2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lengthBtn;
    private javax.swing.JLabel lengthLbl;
    private javax.swing.JTextField lengthTF;
    private javax.swing.JButton locateBtn;
    private javax.swing.JLabel locateLbl;
    private javax.swing.JTextField locateTF1;
    private javax.swing.JTextField locateTF2;
    private javax.swing.JButton replaceBtn;
    private javax.swing.JLabel replaceLbl;
    private javax.swing.JTextField replaceTF;
    // End of variables declaration//GEN-END:variables
}
